//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstate()
        {
            this.Supply = new HashSet<Supply>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AmountRooms { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> Floor { get; set; }
        public string AddressCity { get; set; }
        public string AddressStreet { get; set; }
        public Nullable<int> AddressHouse { get; set; }
        public Nullable<int> AddressNumber { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int TypeRealEstateId { get; set; }
        

        public string FullAddress
        {
           get
            {
                string fullAddress = "";
                if (AddressCity != "")
                {
                    fullAddress += $"г. {AddressCity} ";
                }
                if (AddressStreet != "")
                {
                    fullAddress += $"ул. {AddressStreet} ";
                }
                if (AddressHouse != null)
                {
                    fullAddress += $"д. {AddressHouse} ";
                }
                if (AddressNumber != null)
                {
                    fullAddress += $"кв. {AddressHouse}";
                }
                return fullAddress;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
        public virtual TypeRealEstate TypeRealEstate { get; set; }
    }
}
